### ISSUE TITLE
print("INCOMING> %s" % msg.Body) UnicodeEncodeError

### ISSUE THREAD

**Issue by Sicness** [Sicness/levitan#25]
Exception in thread Skype4Py MessageStatus event scheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/utils.py", line 225, in run
    handler(*self.args, **self.kwargs)
  File "/levitan/skypebot.py", line 19, in MessageStatus
    print("INCOMING> %s" % msg.Body)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-13: ordinal not in range(128)

**Comment by ka2m** [comment]
Which version does it affect? 2.0.1 or latest in repo?

**Comment by Sicness** [comment]
The current master.
https://github.com/Sicness/levitan/commit/2b5cb41ff9b92b2a54206f93e79c466a743ee4f6

**Comment by ka2m** [comment]
I see two ways of solving this issue:

* We add try...catch for this and ignore
* We fix it similar to #18

**Comment by Sicness** [comment]
I'd like to convert the string into needed format..

**Comment by ka2m** [comment]
I suppose, this issue can be delegated to Alina and closed tomorrow

**Comment by Sicness** [comment]
Yes, already delegated.

**Comment by ka2m** [comment]
This seems to be more environment problem, not Levitan's as I'm having messages fine on my Mac. However, I'll do encode-decode thing just in case
