### ISSUE TITLE
Startup fails if finds none of the listed rooms

### ISSUE THREAD

**Issue by ka2m** [Sicness/levitan#31]
```
Traceback (most recent call last):
  File "/Users/fau/Documents/projects/levitan/main.py", line 79, in <module>
    '\n'.join(x.__class__.__name__ for x in plugins))
  File "/Users/fau/Documents/projects/levitan/skypebot.py", line 36, in send
    chat.SendMessage(message)
  File "/Library/Python/2.7/site-packages/Skype4Py/chat.py", line 117, in SendMessage
    tounicode(MessageText))), 2)[1])
  File "/Library/Python/2.7/site-packages/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
Skype4Py.errors.SkypeError: [Errno 511] Sending a message to chat failes
```

I created moderated chat, forgot to rename it and received this. Needs fixing.

**Comment by ka2m** [comment]
I couldn't reproduce it. Some temporary failure. Not important for now.

**Comment by ka2m** [comment]
Ok, seems that it happens when you leave chat, but it still exist (even if there is no users as moderated chats can be empty). I think that's wontfix.

**Comment by Sicness** [comment]
Feel free to close issues by yourself if they are not actual for some reason.

**Comment by ka2m** [comment]
Ok.

On Thursday, March 5, 2015, Anton Balashov <notifications@github.com> wrote:

> Feel free to close issues by yourself if they are not actual for some
> reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sicness/levitan/issues/31#issuecomment-77334336>.
>


-- 
Regards,

Vlad Slepukhin
